GET http://localhost:4000/weather?city=london

#example result type
# {
#   "location": "string",
#   "temperature": number,
#   "weather_descriptions": "string",
#   "wind_speed": number,
#   "humidity": number
# }